openapi: 3.0.0
info:
  title: Kind stalker API
  version: 1.0.0
  contact:
    name: API Support
servers:
  - url: http://localhost
  - url: http://kind-stalker.test
paths:
  /download:
    get:
      security:
        - basicAuth: [ ]
      summary: Download file
      description: Download file
      responses:
        '200':
          description: File downloaded
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /upload:
    post:
      security:
        - basicAuth: [ ]
      summary: Download file
      description: Download file
      parameters:
        - name: Accept
          in: header
          required: false
          schema:
            type: string
            default: application/json
          description: The response format
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                lastImage:
                  type: string
                  format: binary
                  description: The image file to upload.
      responses:
        '201':
          description: File downloaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: File uploaded successfully
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    SimpleMessage:
      type: object
      properties:
        message:
          type: string
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                default: Unauthorized
    Unauthenticated:
      description: Unauthenticated
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                default: Unauthenticated
