name: Laravel CI

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - feature/**

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, intl
        ini-values: post_max_size=256M, max_execution_time=300
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate application key
      run: php artisan key:generate

    - name: Create .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache

    - name: Run PHP CodeSniffer
      run: ./vendor/bin/phpcs --standard=phpcs.xml

    - name: Run PHPUnit tests
      run: php artisan test
